"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = [
    ('resources/images', ['resources/images/logo.icns']),
    ('resources/mp3', [
        'resources/mp3/tomato_done.mp3',
        'resources/mp3/rest_done.mp3',
    ]),
    ('./../Frameworks', ['/opt/homebrew/Cellar/libffi/3.4.4/lib/libffi.8.dylib']),
]
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'resources/images/logo.icns',
    'plist': {
        'CFBundleIdentifier': "com.51zhi.todo"
    },
    'includes': [
    ],
    'packages': [
    ],
    'excludes': [
    ]
}

setup(
    app=APP,
    name='行恒',
    version='0.0.1',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
